### ISSUE TITLE
fileExt.platform

### ISSUE THREAD

**Issue by penghuizhang** [gengchen528/alumin-connect#4]
switch(fileExt.platform) {
                   ^

TypeError: Cannot read property 'platform' of undefined
    at Object.compileToWxml (C:\Users\kylin\Downloads\Compressed\alumin-connect-master\quick-app\node_modules\mpvue-template-compiler\build.js:5785:20)
    at genComponentWxml (C:\Users\kylin\Downloads\Compressed\alumin-connect-master\quick-app\node_modules\mpvue-loader\lib\mp-compiler\index.js:45:75)

是缺少什么依赖包吗？

**Comment by gengchen528** [comment]
> switch(fileExt.platform) {
> ^
> 
> TypeError: Cannot read property 'platform' of undefined
> at Object.compileToWxml (C:\Users\kylin\Downloads\Compressed\alumin-connect-master\quick-app\node_modules\mpvue-template-compiler\build.js:5785:20)
> at genComponentWxml (C:\Users\kylin\Downloads\Compressed\alumin-connect-master\quick-app\node_modules\mpvue-loader\lib\mp-compiler\index.js:45:75)
> 
> 是缺少什么依赖包吗？

已经更新了，你重新拉取一下，删除node_modules,然后重新cnpm install ，  npm  run start:wx;
